/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CarbonEmissionTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addPauser"
      | "addVerifier"
      | "authorizedVerifiers"
      | "closePeriodAndAdvance"
      | "companies"
      | "currentReportingPeriod"
      | "decryptionRequestCounter"
      | "decryptionRequests"
      | "emergencyPause"
      | "emissionReports"
      | "getCompanyInfo"
      | "getCurrentPeriod"
      | "getEncryptedEmissions"
      | "getPauserAtIndex"
      | "getPauserCount"
      | "getPeriodStats"
      | "getRegisteredCompanies"
      | "getReportStatus"
      | "getTotalCompanies"
      | "grantReportAccess"
      | "isContractPaused"
      | "isPaused"
      | "isPauser"
      | "isPauserAddress"
      | "isPeriodValid"
      | "isPublicDecryptAllowed"
      | "isVerifier"
      | "kmsGeneration"
      | "owner"
      | "pause"
      | "pauserAddresses"
      | "periodStats"
      | "registerCompany"
      | "registeredCompanies"
      | "removePauser"
      | "removeVerifier"
      | "requestDecryption"
      | "submitDecryptionResponse"
      | "submitEmissionReport"
      | "totalCompanies"
      | "unpause"
      | "updateKmsGeneration"
      | "verifyCompany"
      | "verifyEmissionReport"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CompanyRegistered"
      | "CompanyVerified"
      | "ContractPaused"
      | "ContractUnpaused"
      | "DecryptionRequested"
      | "DecryptionResponse"
      | "EmissionReported"
      | "KmsGenerationUpdated"
      | "PauserAdded"
      | "PauserRemoved"
      | "PeriodClosed"
      | "ReportVerified"
      | "VerifierAdded"
      | "VerifierRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addPauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedVerifiers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closePeriodAndAdvance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "companies",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentReportingPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionRequestCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emissionReports",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCompanyInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedEmissions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPauserAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPauserCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPeriodStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegisteredCompanies",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReportStatus",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCompanies",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantReportAccess",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isContractPaused",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isPauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPauserAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPeriodValid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPublicDecryptAllowed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "kmsGeneration",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauserAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "periodStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCompany",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredCompanies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removePauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestDecryption",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitDecryptionResponse",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEmissionReport",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCompanies",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateKmsGeneration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCompany",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyEmissionReport",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addPauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closePeriodAndAdvance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "companies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentReportingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionRequestCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emissionReports",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCompanyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedEmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPauserAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPauserCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPeriodStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegisteredCompanies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReportStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCompanies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantReportAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isContractPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPauserAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPeriodValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPublicDecryptAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "kmsGeneration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauserAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "periodStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredCompanies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePauser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitDecryptionResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEmissionReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCompanies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateKmsGeneration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyEmissionReport",
    data: BytesLike
  ): Result;
}

export namespace CompanyRegisteredEvent {
  export type InputTuple = [company: AddressLike, name: string];
  export type OutputTuple = [company: string, name: string];
  export interface OutputObject {
    company: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CompanyVerifiedEvent {
  export type InputTuple = [company: AddressLike, verifier: AddressLike];
  export type OutputTuple = [company: string, verifier: string];
  export interface OutputObject {
    company: string;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractPausedEvent {
  export type InputTuple = [by: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [by: string, timestamp: bigint];
  export interface OutputObject {
    by: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractUnpausedEvent {
  export type InputTuple = [by: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [by: string, timestamp: bigint];
  export interface OutputObject {
    by: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    requester: AddressLike,
    kmsGeneration: BigNumberish,
    encryptedValue: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    requester: string,
    kmsGeneration: bigint,
    encryptedValue: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    requester: string;
    kmsGeneration: bigint;
    encryptedValue: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionResponseEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    kmsNode: AddressLike,
    encryptedShare: BytesLike,
    signature: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    kmsNode: string,
    encryptedShare: string,
    signature: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    kmsNode: string;
    encryptedShare: string;
    signature: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmissionReportedEvent {
  export type InputTuple = [company: AddressLike, period: BigNumberish];
  export type OutputTuple = [company: string, period: bigint];
  export interface OutputObject {
    company: string;
    period: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KmsGenerationUpdatedEvent {
  export type InputTuple = [
    oldGeneration: BigNumberish,
    newGeneration: BigNumberish
  ];
  export type OutputTuple = [oldGeneration: bigint, newGeneration: bigint];
  export interface OutputObject {
    oldGeneration: bigint;
    newGeneration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauserAddedEvent {
  export type InputTuple = [pauser: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [pauser: string, timestamp: bigint];
  export interface OutputObject {
    pauser: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauserRemovedEvent {
  export type InputTuple = [pauser: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [pauser: string, timestamp: bigint];
  export interface OutputObject {
    pauser: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PeriodClosedEvent {
  export type InputTuple = [
    period: BigNumberish,
    participatingCompanies: BigNumberish
  ];
  export type OutputTuple = [period: bigint, participatingCompanies: bigint];
  export interface OutputObject {
    period: bigint;
    participatingCompanies: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReportVerifiedEvent {
  export type InputTuple = [
    company: AddressLike,
    period: BigNumberish,
    verifier: AddressLike
  ];
  export type OutputTuple = [company: string, period: bigint, verifier: string];
  export interface OutputObject {
    company: string;
    period: bigint;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierAddedEvent {
  export type InputTuple = [verifier: AddressLike];
  export type OutputTuple = [verifier: string];
  export interface OutputObject {
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierRemovedEvent {
  export type InputTuple = [verifier: AddressLike];
  export type OutputTuple = [verifier: string];
  export interface OutputObject {
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CarbonEmissionTracker extends BaseContract {
  connect(runner?: ContractRunner | null): CarbonEmissionTracker;
  waitForDeployment(): Promise<this>;

  interface: CarbonEmissionTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addPauser: TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;

  addVerifier: TypedContractMethod<
    [_verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedVerifiers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  closePeriodAndAdvance: TypedContractMethod<[], [void], "nonpayable">;

  companies: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, boolean, bigint] & {
        wallet: string;
        name: string;
        isRegistered: boolean;
        isVerified: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  currentReportingPeriod: TypedContractMethod<[], [bigint], "view">;

  decryptionRequestCounter: TypedContractMethod<[], [bigint], "view">;

  decryptionRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean, bigint] & {
        requestId: bigint;
        requester: string;
        encryptedValue: string;
        timestamp: bigint;
        fulfilled: boolean;
        kmsGeneration: bigint;
      }
    ],
    "view"
  >;

  emergencyPause: TypedContractMethod<[], [void], "nonpayable">;

  emissionReports: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, string, bigint, bigint, boolean, boolean] & {
        encryptedDirectEmissions: string;
        encryptedIndirectEmissions: string;
        encryptedSupplyChainEmissions: string;
        encryptedEnergyConsumption: string;
        reportingPeriod: bigint;
        timestamp: bigint;
        isSubmitted: boolean;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  getCompanyInfo: TypedContractMethod<
    [_company: AddressLike],
    [
      [string, boolean, boolean, bigint] & {
        name: string;
        isRegistered: boolean;
        isVerified: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  getCurrentPeriod: TypedContractMethod<[], [bigint], "view">;

  getEncryptedEmissions: TypedContractMethod<
    [_company: AddressLike, _period: BigNumberish],
    [
      [string, string, string, string] & {
        directEmissions: string;
        indirectEmissions: string;
        supplyChainEmissions: string;
        energyConsumption: string;
      }
    ],
    "view"
  >;

  getPauserAtIndex: TypedContractMethod<
    [_index: BigNumberish],
    [string],
    "view"
  >;

  getPauserCount: TypedContractMethod<[], [bigint], "view">;

  getPeriodStats: TypedContractMethod<
    [_period: BigNumberish],
    [
      [bigint, bigint, boolean, bigint] & {
        participatingCompanies: bigint;
        totalReports: bigint;
        periodClosed: boolean;
        closeTime: bigint;
      }
    ],
    "view"
  >;

  getRegisteredCompanies: TypedContractMethod<[], [string[]], "view">;

  getReportStatus: TypedContractMethod<
    [_company: AddressLike, _period: BigNumberish],
    [
      [boolean, boolean, bigint] & {
        isSubmitted: boolean;
        isVerified: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getTotalCompanies: TypedContractMethod<[], [bigint], "view">;

  grantReportAccess: TypedContractMethod<
    [_to: AddressLike, _period: BigNumberish],
    [void],
    "nonpayable"
  >;

  isContractPaused: TypedContractMethod<[], [boolean], "view">;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  isPauser: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  isPauserAddress: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isPeriodValid: TypedContractMethod<
    [_period: BigNumberish],
    [boolean],
    "view"
  >;

  isPublicDecryptAllowed: TypedContractMethod<[], [boolean], "view">;

  isVerifier: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  kmsGeneration: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  pauserAddresses: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  periodStats: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean, bigint] & {
        participatingCompanies: bigint;
        totalReports: bigint;
        periodClosed: boolean;
        closeTime: bigint;
      }
    ],
    "view"
  >;

  registerCompany: TypedContractMethod<[_name: string], [void], "nonpayable">;

  registeredCompanies: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  removePauser: TypedContractMethod<
    [_pauser: AddressLike],
    [void],
    "nonpayable"
  >;

  removeVerifier: TypedContractMethod<
    [_verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  requestDecryption: TypedContractMethod<
    [_encryptedValue: BytesLike],
    [bigint],
    "nonpayable"
  >;

  submitDecryptionResponse: TypedContractMethod<
    [
      _requestId: BigNumberish,
      _encryptedShare: BytesLike,
      _signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  submitEmissionReport: TypedContractMethod<
    [
      _directEmissions: BigNumberish,
      _indirectEmissions: BigNumberish,
      _supplyChainEmissions: BigNumberish,
      _energyConsumption: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  totalCompanies: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateKmsGeneration: TypedContractMethod<
    [_newGeneration: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyCompany: TypedContractMethod<
    [_company: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyEmissionReport: TypedContractMethod<
    [_company: AddressLike, _period: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addPauser"
  ): TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addVerifier"
  ): TypedContractMethod<[_verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedVerifiers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "closePeriodAndAdvance"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "companies"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, boolean, bigint] & {
        wallet: string;
        name: string;
        isRegistered: boolean;
        isVerified: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "currentReportingPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decryptionRequestCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decryptionRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean, bigint] & {
        requestId: bigint;
        requester: string;
        encryptedValue: string;
        timestamp: bigint;
        fulfilled: boolean;
        kmsGeneration: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emissionReports"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, string, bigint, bigint, boolean, boolean] & {
        encryptedDirectEmissions: string;
        encryptedIndirectEmissions: string;
        encryptedSupplyChainEmissions: string;
        encryptedEnergyConsumption: string;
        reportingPeriod: bigint;
        timestamp: bigint;
        isSubmitted: boolean;
        isVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCompanyInfo"
  ): TypedContractMethod<
    [_company: AddressLike],
    [
      [string, boolean, boolean, bigint] & {
        name: string;
        isRegistered: boolean;
        isVerified: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedEmissions"
  ): TypedContractMethod<
    [_company: AddressLike, _period: BigNumberish],
    [
      [string, string, string, string] & {
        directEmissions: string;
        indirectEmissions: string;
        supplyChainEmissions: string;
        energyConsumption: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPauserAtIndex"
  ): TypedContractMethod<[_index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPauserCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPeriodStats"
  ): TypedContractMethod<
    [_period: BigNumberish],
    [
      [bigint, bigint, boolean, bigint] & {
        participatingCompanies: bigint;
        totalReports: bigint;
        periodClosed: boolean;
        closeTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRegisteredCompanies"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getReportStatus"
  ): TypedContractMethod<
    [_company: AddressLike, _period: BigNumberish],
    [
      [boolean, boolean, bigint] & {
        isSubmitted: boolean;
        isVerified: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalCompanies"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantReportAccess"
  ): TypedContractMethod<
    [_to: AddressLike, _period: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isContractPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPauser"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPauserAddress"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPeriodValid"
  ): TypedContractMethod<[_period: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPublicDecryptAllowed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVerifier"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "kmsGeneration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pauserAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "periodStats"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean, bigint] & {
        participatingCompanies: bigint;
        totalReports: bigint;
        periodClosed: boolean;
        closeTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerCompany"
  ): TypedContractMethod<[_name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registeredCompanies"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "removePauser"
  ): TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeVerifier"
  ): TypedContractMethod<[_verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestDecryption"
  ): TypedContractMethod<[_encryptedValue: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "submitDecryptionResponse"
  ): TypedContractMethod<
    [
      _requestId: BigNumberish,
      _encryptedShare: BytesLike,
      _signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitEmissionReport"
  ): TypedContractMethod<
    [
      _directEmissions: BigNumberish,
      _indirectEmissions: BigNumberish,
      _supplyChainEmissions: BigNumberish,
      _energyConsumption: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalCompanies"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateKmsGeneration"
  ): TypedContractMethod<[_newGeneration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyCompany"
  ): TypedContractMethod<[_company: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyEmissionReport"
  ): TypedContractMethod<
    [_company: AddressLike, _period: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CompanyRegistered"
  ): TypedContractEvent<
    CompanyRegisteredEvent.InputTuple,
    CompanyRegisteredEvent.OutputTuple,
    CompanyRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CompanyVerified"
  ): TypedContractEvent<
    CompanyVerifiedEvent.InputTuple,
    CompanyVerifiedEvent.OutputTuple,
    CompanyVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "ContractPaused"
  ): TypedContractEvent<
    ContractPausedEvent.InputTuple,
    ContractPausedEvent.OutputTuple,
    ContractPausedEvent.OutputObject
  >;
  getEvent(
    key: "ContractUnpaused"
  ): TypedContractEvent<
    ContractUnpausedEvent.InputTuple,
    ContractUnpausedEvent.OutputTuple,
    ContractUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionRequested"
  ): TypedContractEvent<
    DecryptionRequestedEvent.InputTuple,
    DecryptionRequestedEvent.OutputTuple,
    DecryptionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionResponse"
  ): TypedContractEvent<
    DecryptionResponseEvent.InputTuple,
    DecryptionResponseEvent.OutputTuple,
    DecryptionResponseEvent.OutputObject
  >;
  getEvent(
    key: "EmissionReported"
  ): TypedContractEvent<
    EmissionReportedEvent.InputTuple,
    EmissionReportedEvent.OutputTuple,
    EmissionReportedEvent.OutputObject
  >;
  getEvent(
    key: "KmsGenerationUpdated"
  ): TypedContractEvent<
    KmsGenerationUpdatedEvent.InputTuple,
    KmsGenerationUpdatedEvent.OutputTuple,
    KmsGenerationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PauserAdded"
  ): TypedContractEvent<
    PauserAddedEvent.InputTuple,
    PauserAddedEvent.OutputTuple,
    PauserAddedEvent.OutputObject
  >;
  getEvent(
    key: "PauserRemoved"
  ): TypedContractEvent<
    PauserRemovedEvent.InputTuple,
    PauserRemovedEvent.OutputTuple,
    PauserRemovedEvent.OutputObject
  >;
  getEvent(
    key: "PeriodClosed"
  ): TypedContractEvent<
    PeriodClosedEvent.InputTuple,
    PeriodClosedEvent.OutputTuple,
    PeriodClosedEvent.OutputObject
  >;
  getEvent(
    key: "ReportVerified"
  ): TypedContractEvent<
    ReportVerifiedEvent.InputTuple,
    ReportVerifiedEvent.OutputTuple,
    ReportVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierAdded"
  ): TypedContractEvent<
    VerifierAddedEvent.InputTuple,
    VerifierAddedEvent.OutputTuple,
    VerifierAddedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierRemoved"
  ): TypedContractEvent<
    VerifierRemovedEvent.InputTuple,
    VerifierRemovedEvent.OutputTuple,
    VerifierRemovedEvent.OutputObject
  >;

  filters: {
    "CompanyRegistered(address,string)": TypedContractEvent<
      CompanyRegisteredEvent.InputTuple,
      CompanyRegisteredEvent.OutputTuple,
      CompanyRegisteredEvent.OutputObject
    >;
    CompanyRegistered: TypedContractEvent<
      CompanyRegisteredEvent.InputTuple,
      CompanyRegisteredEvent.OutputTuple,
      CompanyRegisteredEvent.OutputObject
    >;

    "CompanyVerified(address,address)": TypedContractEvent<
      CompanyVerifiedEvent.InputTuple,
      CompanyVerifiedEvent.OutputTuple,
      CompanyVerifiedEvent.OutputObject
    >;
    CompanyVerified: TypedContractEvent<
      CompanyVerifiedEvent.InputTuple,
      CompanyVerifiedEvent.OutputTuple,
      CompanyVerifiedEvent.OutputObject
    >;

    "ContractPaused(address,uint256)": TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;
    ContractPaused: TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;

    "ContractUnpaused(address,uint256)": TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;
    ContractUnpaused: TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;

    "DecryptionRequested(uint256,address,uint256,bytes32,uint256)": TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;
    DecryptionRequested: TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;

    "DecryptionResponse(uint256,address,bytes,bytes,uint256)": TypedContractEvent<
      DecryptionResponseEvent.InputTuple,
      DecryptionResponseEvent.OutputTuple,
      DecryptionResponseEvent.OutputObject
    >;
    DecryptionResponse: TypedContractEvent<
      DecryptionResponseEvent.InputTuple,
      DecryptionResponseEvent.OutputTuple,
      DecryptionResponseEvent.OutputObject
    >;

    "EmissionReported(address,uint256)": TypedContractEvent<
      EmissionReportedEvent.InputTuple,
      EmissionReportedEvent.OutputTuple,
      EmissionReportedEvent.OutputObject
    >;
    EmissionReported: TypedContractEvent<
      EmissionReportedEvent.InputTuple,
      EmissionReportedEvent.OutputTuple,
      EmissionReportedEvent.OutputObject
    >;

    "KmsGenerationUpdated(uint256,uint256)": TypedContractEvent<
      KmsGenerationUpdatedEvent.InputTuple,
      KmsGenerationUpdatedEvent.OutputTuple,
      KmsGenerationUpdatedEvent.OutputObject
    >;
    KmsGenerationUpdated: TypedContractEvent<
      KmsGenerationUpdatedEvent.InputTuple,
      KmsGenerationUpdatedEvent.OutputTuple,
      KmsGenerationUpdatedEvent.OutputObject
    >;

    "PauserAdded(address,uint256)": TypedContractEvent<
      PauserAddedEvent.InputTuple,
      PauserAddedEvent.OutputTuple,
      PauserAddedEvent.OutputObject
    >;
    PauserAdded: TypedContractEvent<
      PauserAddedEvent.InputTuple,
      PauserAddedEvent.OutputTuple,
      PauserAddedEvent.OutputObject
    >;

    "PauserRemoved(address,uint256)": TypedContractEvent<
      PauserRemovedEvent.InputTuple,
      PauserRemovedEvent.OutputTuple,
      PauserRemovedEvent.OutputObject
    >;
    PauserRemoved: TypedContractEvent<
      PauserRemovedEvent.InputTuple,
      PauserRemovedEvent.OutputTuple,
      PauserRemovedEvent.OutputObject
    >;

    "PeriodClosed(uint256,uint256)": TypedContractEvent<
      PeriodClosedEvent.InputTuple,
      PeriodClosedEvent.OutputTuple,
      PeriodClosedEvent.OutputObject
    >;
    PeriodClosed: TypedContractEvent<
      PeriodClosedEvent.InputTuple,
      PeriodClosedEvent.OutputTuple,
      PeriodClosedEvent.OutputObject
    >;

    "ReportVerified(address,uint256,address)": TypedContractEvent<
      ReportVerifiedEvent.InputTuple,
      ReportVerifiedEvent.OutputTuple,
      ReportVerifiedEvent.OutputObject
    >;
    ReportVerified: TypedContractEvent<
      ReportVerifiedEvent.InputTuple,
      ReportVerifiedEvent.OutputTuple,
      ReportVerifiedEvent.OutputObject
    >;

    "VerifierAdded(address)": TypedContractEvent<
      VerifierAddedEvent.InputTuple,
      VerifierAddedEvent.OutputTuple,
      VerifierAddedEvent.OutputObject
    >;
    VerifierAdded: TypedContractEvent<
      VerifierAddedEvent.InputTuple,
      VerifierAddedEvent.OutputTuple,
      VerifierAddedEvent.OutputObject
    >;

    "VerifierRemoved(address)": TypedContractEvent<
      VerifierRemovedEvent.InputTuple,
      VerifierRemovedEvent.OutputTuple,
      VerifierRemovedEvent.OutputObject
    >;
    VerifierRemoved: TypedContractEvent<
      VerifierRemovedEvent.InputTuple,
      VerifierRemovedEvent.OutputTuple,
      VerifierRemovedEvent.OutputObject
    >;
  };
}
